server:
  persistentVolume:
    # -- Create/use Persistent Volume Claim for server component. Use empty dir if set to false
    enabled: true
    accessModes:
      - ReadWriteOnce
    storageClassName: standard
    mountPath: /storage
    size: 4Gi

  service:
    nodePort: 30000
    # -- Service type
    type: NodePort

  mode: statefulSet
  
vector:
  # -- Enable deployment of vector
  enabled: true
  role: Agent
  dataDir: /vector-data-dir
  resources: {}
  args:
    - -w
    - --config-dir
    - /etc/vector/
  containerPorts:
    - name: prom-exporter
      containerPort: 9090
      protocol: TCP
  service:
    enabled: false
  existingConfigMaps:
    - vector-vl-config
  # -- Forces custom configuration creation in a given namespace even if vector.enabled is false
  customConfigNamespace: ""
  customConfigName: vector-vl-config
  customConfig:
    data_dir: /vector-data-dir
    api:
      enabled: false
      address: 0.0.0.0:8686
    sources:
      k8s:
        type: kubernetes_logs
      internal_metrics:
        type: internal_metrics
    transforms:
      parser:
        type: remap
        inputs: [k8s]
        source: |
          .log = parse_json(.message) ?? .message
          del(.message)
    sinks:
      exporter:
        type: prometheus_exporter
        address: 0.0.0.0:9090
        inputs: [internal_metrics]
      vlogs:
        type: elasticsearch
        inputs: [parser]
        mode: bulk
        api_version: v8
        compression: gzip
        healthcheck:
          enabled: false
        request:
          headers:
            VL-Time-Field: timestamp
            VL-Stream-Fields: stream,kubernetes.pod_name,kubernetes.container_name,kubernetes.pod_namespace
            VL-Msg-Field: message,msg,_msg,log.msg,log.message,log
            AccountID: "0"
            ProjectID: "0"

dashboards:
  # -- Create VictoriaLogs dashboards
  enabled: true
  # -- Dashboard labels
  labels: {}
  #  grafana_dashboard: "1"
  # -- Dashboard annotations
  annotations: {}
  # -- Override default namespace, where to create dashboards
  namespace: ""
  grafanaOperator:
    enabled: false
    spec:
      instanceSelector:
        matchLabels:
          dashboards: "grafana"
      allowCrossNamespaceImport: false
