singleNode: true

# The service that non master groups will try to connect to when joining the cluster
# This should be set to clusterName + "-" + nodeGroup for your master group
masterService: "opensearch-cluster-master"

# OpenSearch roles that will be applied to this nodeGroup
# These will be set as environment variable "node.roles". E.g. node.roles=master,ingest,data,remote_cluster_client
roles:
  - master
  - ingest
  - data
  - remote_cluster_client

replicas: 1

opensearchHome: /usr/share/opensearch

extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: Chrlghk#123

# Allows you to load environment variables from kubernetes secret or config map
envFrom: []
# - secretRef:
#     name: env-secret
# - configMapRef:
#     name: config-map

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "4Gi"
  
networkHost: "0.0.0.0"

opensearchJavaOpts: "-Xms2g -Xmx2g"

service:
  type: NodePort
  nodePort: 30092
  port: 9200

persistence:
  enabled: true
  # Set to false to disable the `fsgroup-volume` initContainer that will update permissions on the persistent disk.
  enableInitChown: true
  # override image, which is busybox by default
  # image: busybox
  # override image tag, which is latest by default
  # imageTag:
  labels:
    # KÍCH HOẠT cấu hình label cho volumeClaimTemplate
    enabled: true
    # THÊM custom label của bạn tại đây
    additionalLabels: 
      environment: dev
  # Sử dụng Storage Class "local-path" của cụm kind
  storageClass: "standard"
  accessModes:
    - ReadWriteOnce
  size: 4Gi
  annotations: {}

# Quan trọng: local-path-provisioner của kind không hỗ trợ mở rộng Volume (Volume Expansion)
# Do đó phải tắt tính năng này để tránh lỗi khi Helm khởi tạo StatefulSet
sysctlVmMaxMapCount: 262144

extraVolumes: []
  # - name: extras
  #   emptyDir: {}

extraVolumeMounts: []
  # - name: extras
  #   mountPath: /usr/share/extras
  #   readOnly: true

