[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf
[INPUT]
    Name             tail
    Tag              nginx.logs
    Path             /var/log/nginx/*.log
    DB               /fluent-bit/etc/nginx-logs.db
    Read_From_Head   false
[FILTER]
    Name         parser
    Match        nginx.logs
    Key_Name     log
    Parser       parse_request
    Preserve_Key On
    Reserve_Data On
[FILTER]
    Name             record_modifier
    Match            nginx.logs
    Record environment development
[OUTPUT]
    name opensearch
    match nginx.logs
    host 172.19.0.2
    port  30092
    tls             On
    tls.verify      Off
    http_user admin
    http_passwd Chrlghk#123
    index nginx-logs
    type  _doc
    suppress_type_name  On
    Logstash_Format     On
    Logstash_Prefix     nginx-logs
    Logstash_DateFormat %Y.%m.%d
[OUTPUT]
    Name http
    Match *
    host 172.19.0.2
    port 30000
    uri /insert/jsonline?_stream_fields=stream&_msg_field=log&_time_field=date&debug=1
    format json_lines
    json_date_format iso8601
    HTTP_User           0
    HTTP_Passwd         0
