[PARSER]
  Name parse_request
  Format regex
  Regex /^(?<ip_request>.+) - - \[(?<time>.+)\] \"(?<http_method>.+) (?<request_path>[^\s]+)\s+(?<protocol>[^\s"]+)"\s+(?<status>\d+)\s+(?<body_bytes_sent>\d+)\s+"(?<referer>[^"]*)"\s+"(?<user_agent>[^"]*)"$/
